name: carbonic_template
description: A template app by carbonic
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # dart
  collection: ^1.18.0
  dart_date: ^1.3.2

  # firebase
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  firebase_messaging: ^14.7.10

  # core system
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.1
  dio: ^5.4.0
  flutter_local_notifications: ^16.3.2

  # annotation
  riverpod_annotation: ^2.3.3
  retrofit: ^4.0.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # tools
  sentry_flutter: ^7.14.0
  sentry_dio: ^7.15.0
  appsflyer_sdk: ^6.12.2

  # ui
  gap: ^3.0.1
  loader_overlay: ^4.0.0
  cached_network_image: ^3.3.1
  lottie: ^3.0.0
  flutter_animate: ^4.5.0
  custom_refresh_indicator: ^3.0.0
  flutter_widget_from_html_core: ^0.14.11

  # utility
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.4
  app_links: ^3.5.0
  get_storage: ^2.1.1
  permission_handler: ^11.2.0
  flutter_email_sender: ^6.0.2
  flutter_keyboard_visibility: ^6.0.0
  flutter_secure_storage: ^9.0.0
  device_info_plus: ^9.1.2
  package_info_plus: ^5.0.1
  get_it: ^7.6.7
  local_auth: ^2.1.8
  local_auth_android: ^1.0.36
  local_auth_ios: ^1.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8 # dart run build_runner build --delete-conflicting-outputs

  flutter_flavorizr: ^2.2.1

  # lint
  flutter_lints: ^3.0.1
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7

  # generator
  riverpod_generator: ^2.3.9
  retrofit_generator: ^8.0.6
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  pigeon: ^16.0.4

  # tools
  sentry_dart_plugin: ^1.6.0

flutter:
  uses-material-design: true

  assets:
    - asset/feature/open_source_license/
    - asset/feature/splash/

  fonts:
    - family: Pretendard
      fonts:
        - asset: asset/font/Pretendard-Thin.ttf
          weight: 100
        - asset: asset/font/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: asset/font/Pretendard-Light.ttf
          weight: 300
        - asset: asset/font/Pretendard-Regular.ttf
          weight: 400
        - asset: asset/font/Pretendard-Medium.ttf
          weight: 500
        - asset: asset/font/Pretendard-SemiBold.ttf
          weight: 600
        - asset: asset/font/Pretendard-Bold.ttf
          weight: 700
        - asset: asset/font/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: asset/font/Pretendard-Black.ttf
          weight: 900

sentry:
  project: TODO
  org: TODO
  auth_token: TODO
  upload_sources: true
  ignore_missing: true
