# Melos Configuration: https://melos.invertase.dev/configuration/overview

name: carbonic

repository: https://github.com/marsg6/carbonic

packages:
  - ./**

command:
  bootstrap:
    dev_dependencies:
      build_runner: ^2.4.8

    hooks:
      pre: make -f bootstrap_pre.mk
      post: make -f bootstrap_post.mk

  version:
    branch: main

scripts:
  # 패키지 Publish 관련
  validate: melos publish --ignore="open_source_license" --yes
  upload: melos publish --ignore="open_source_license" --no-dry-run --yes --verbose
