# Melos Configuration: https://melos.invertase.dev/configuration/overview

name: carbonic

repository: https://github.com/marsg6/carbonic

packages:
  - ./**

command:
  version:
    branch: main

  bootstrap:
    dev_dependencies:
      build_runner: ^2.4.8

    hooks:
      pre: make -f bootstrap_pre.mk
      post: make -f bootstrap_post.mk

scripts:
  # 패키지 Publish 관련
  validate: melos publish --scope="package/**" --verbose
  upload: melos publish --scope="package/**" --no-dry-run --verbose
