name: carbonic

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  melos: ^4.1.0

  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11
  retrofit_generator: ^8.1.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
