# Melos Configuration: https://melos.invertase.dev/configuration/overview

name: carbonic

repository: https://github.com/marsg6/carbonic

packages:
  - package/**

command:
  version:
    branch: main
